//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources.Exam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Actionexam___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Actionexam___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppResources.Exam.Actionexam - Copy", typeof(Actionexam___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subject.
        /// </summary>
        public static string AddSubject {
            get {
                return ResourceManager.GetString("AddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditSubject.
        /// </summary>
        public static string EditSubject {
            get {
                return ResourceManager.GetString("EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Exam.
        /// </summary>
        public static string Exam_Final {
            get {
                return ResourceManager.GetString("Exam_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makeup Exam.
        /// </summary>
        public static string Exam_Makeup {
            get {
                return ResourceManager.GetString("Exam_Makeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midterm Exam.
        /// </summary>
        public static string Exam_MidTerm {
            get {
                return ResourceManager.GetString("Exam_MidTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement Test.
        /// </summary>
        public static string Exam_Placement {
            get {
                return ResourceManager.GetString("Exam_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Test.
        /// </summary>
        public static string Exam_Practice {
            get {
                return ResourceManager.GetString("Exam_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        public static string Exam_Quiz {
            get {
                return ResourceManager.GetString("Exam_Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Subject_Arabic {
            get {
                return ResourceManager.GetString("Subject_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biology.
        /// </summary>
        public static string Subject_Biology {
            get {
                return ResourceManager.GetString("Subject_Biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry.
        /// </summary>
        public static string Subject_Chemistry {
            get {
                return ResourceManager.GetString("Subject_Chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Science.
        /// </summary>
        public static string Subject_Computer {
            get {
                return ResourceManager.GetString("Subject_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Subject_English {
            get {
                return ResourceManager.GetString("Subject_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        public static string Subject_Geography {
            get {
                return ResourceManager.GetString("Subject_Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Subject_History {
            get {
                return ResourceManager.GetString("Subject_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematics.
        /// </summary>
        public static string Subject_Math {
            get {
                return ResourceManager.GetString("Subject_Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics.
        /// </summary>
        public static string Subject_Physics {
            get {
                return ResourceManager.GetString("Subject_Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
    }
}
