//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources.Exam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Actionexam {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Actionexam() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppResources.Exam.Actionexam", typeof(Actionexam).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exam.
        /// </summary>
        public static string Action_AddExam {
            get {
                return ResourceManager.GetString("Action_AddExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string Action_AddQuestion {
            get {
                return ResourceManager.GetString("Action_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subject.
        /// </summary>
        public static string Action_AddSubject {
            get {
                return ResourceManager.GetString("Action_AddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Exam.
        /// </summary>
        public static string Action_DeleteExam {
            get {
                return ResourceManager.GetString("Action_DeleteExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Subject.
        /// </summary>
        public static string Action_DeleteSubject {
            get {
                return ResourceManager.GetString("Action_DeleteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Exam.
        /// </summary>
        public static string Action_EditExam {
            get {
                return ResourceManager.GetString("Action_EditExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        public static string Action_EditQuestion {
            get {
                return ResourceManager.GetString("Action_EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Subject.
        /// </summary>
        public static string Action_EditSubject {
            get {
                return ResourceManager.GetString("Action_EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Exam.
        /// </summary>
        public static string Action_RetryExam {
            get {
                return ResourceManager.GetString("Action_RetryExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Exam.
        /// </summary>
        public static string Action_ShowExam {
            get {
                return ResourceManager.GetString("Action_ShowExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Exams.
        /// </summary>
        public static string Action_ShowExams {
            get {
                return ResourceManager.GetString("Action_ShowExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Question.
        /// </summary>
        public static string Action_ShowQuestion {
            get {
                return ResourceManager.GetString("Action_ShowQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Questions.
        /// </summary>
        public static string Action_ShowQuestions {
            get {
                return ResourceManager.GetString("Action_ShowQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Exam.
        /// </summary>
        public static string Action_StartExam {
            get {
                return ResourceManager.GetString("Action_StartExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Exam.
        /// </summary>
        public static string Action_SubmitExam {
            get {
                return ResourceManager.GetString("Action_SubmitExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Exam Result.
        /// </summary>
        public static string Action_ViewExamResult {
            get {
                return ResourceManager.GetString("Action_ViewExamResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Subject Details.
        /// </summary>
        public static string Action_ViewSubjectDetails {
            get {
                return ResourceManager.GetString("Action_ViewSubjectDetails", resourceCulture);
            }
        }
    }
}
